### ISSUE TITLE
Fix notification Dialog Layout

### ISSUE THREAD

**Issue by DanielHabenicht** [T-Systems-MMS/phonebook#186]
![image](https://user-images.githubusercontent.com/13590797/63416442-aee79480-c3ff-11e9-8699-b5cfc3e362d5.png)

The Problem is with `.mat-dialog-content` class adding a `max-height: 65vh`. 

In order to resolve this bug add this to the overwrite.scss:
```scss
.mat-dialog-content {
     max-height: unset;
}
```
